// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/wiardvanrij/gitorchestrator/pkg/apis/gitorchestrator/v1alpha1.GitOrchestrator":       schema_pkg_apis_gitorchestrator_v1alpha1_GitOrchestrator(ref),
		"github.com/wiardvanrij/gitorchestrator/pkg/apis/gitorchestrator/v1alpha1.GitOrchestratorSpec":   schema_pkg_apis_gitorchestrator_v1alpha1_GitOrchestratorSpec(ref),
		"github.com/wiardvanrij/gitorchestrator/pkg/apis/gitorchestrator/v1alpha1.GitOrchestratorStatus": schema_pkg_apis_gitorchestrator_v1alpha1_GitOrchestratorStatus(ref),
	}
}

func schema_pkg_apis_gitorchestrator_v1alpha1_GitOrchestrator(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GitOrchestrator is the Schema for the gitorchestrators API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/wiardvanrij/gitorchestrator/pkg/apis/gitorchestrator/v1alpha1.GitOrchestratorSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/wiardvanrij/gitorchestrator/pkg/apis/gitorchestrator/v1alpha1.GitOrchestratorStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/wiardvanrij/gitorchestrator/pkg/apis/gitorchestrator/v1alpha1.GitOrchestratorSpec", "github.com/wiardvanrij/gitorchestrator/pkg/apis/gitorchestrator/v1alpha1.GitOrchestratorStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_gitorchestrator_v1alpha1_GitOrchestratorSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GitOrchestratorSpec defines the desired state of GitOrchestrator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_gitorchestrator_v1alpha1_GitOrchestratorStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GitOrchestratorStatus defines the observed state of GitOrchestrator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
